### PR TITLE
Hides Close button on Home Page

### LINKED ISSUE #10: Fix close button for PWA
The close button doesn't work on PWA (Mobile App).

### PR DESCRIPTION
**Pull request by eemike07**
Resolves #10 

Due to security constraints of the Web Browser, closing the Window will not work.
So I had to resort to hiding the Close on the Home Page.

https://stackoverflow.com/questions/19761241/window-close-and-self-close-do-not-close-the-window-in-chrome

### CODE REVIEW

**Comment by eemike07** [comment]
@yashchaudhari008  - hey, why was the `hacktoberfest-accepted` tag removed?  Was there additional changes required to accept this PR?

**Comment by yashchaudhari008** [comment]
Yes, check the comment

**Comment by eemike07** [comment]
> Yes, check the comment

`Else if not possible , you can hide it` - I hide it.

**Comment by yashchaudhari008** [comment]
No worries, i will edit and merge ✌️

**Pull request merged**
